datasource:
  default: ${APP_ENV}
  development:
    username: sa
    password: sa
    url: "jdbc:h2:./database"
  production:
    username: afdzzrmhchrgac
    password: ce78637daae42675059ac8cf7815bda65a5ca2d6daaf71bcf0d1c7292f2e6199
    url: postgres://afdzzrmhchrgac:ce78637daae42675059ac8cf7815bda65a5ca2d6daaf71bcf0d1c7292f2e6199@ec2-107-22-122-106.compute-1.amazonaws.com:5432/d21a9dmqo6rup3

ebean:
  migration:
    run: true