name: gitHub actions
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.2
      - uses: actions/setup-java@v3.4.1
      - uses: gradle/gradle-build-action@v2.2.1
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Build with Gradle
        run: make build

